# fly.toml app configuration file generated for myipcio on 2024-01-06T07:48:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "myipcio"
primary_region = "sjc"

[build]

[http_service]
  # internal_port = 8080
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
